language: perl
matrix:
  include:
  - perl: '5.12'
    dist: trusty
  - perl: '5.14'
  - perl: '5.16'
  - perl: '5.18'
  - perl: '5.20'
  - perl: '5.22'
  - perl: '5.24'
  - perl: '5.26'
  - perl: '5.28'
  - perl: '5.30'
notifications:
  slack:
    secure: ykmspnS/gX9GspqZRZOeDA1PWWTabETooMdf6iTtsKyenpV57jtYsAAhma84PJXvl+3A8W4+4/d8HbdjfIXyvoYovzi/GS1oYUM5xgQh9pqyczh0/tDWgcmhdQoC9xQfMMMci9gIHpymoSruvsWeNhKwAhtkVvv0QcHYysESLXfXowHcw9jR3PtBiey23a0ApjGwJnrqlNC1n/mXRTPIz8Mx5DC1w9sjSHoozuIZBnojyHB1NHzdL2DMa/OK3pOl3+TQz8fMHsrydT3fUyeSP7CLlIsPj2cGOoiaYOtfaXWyms33XlA5DSMgc6GjBzLKEsijtL1k405dpkYWdn0hYhMcEPLykNdJGDFvES8ROi+LTnWMeBv6ouXzxjrW0ekkmW+YIH3kXp6BhNsy/Mh/ITM3sgFuRB5w6clC73sdOLXUuUMuUznzfMCl0uhvcw051xdQhGDiO4+gDNqmC6clFunu3eVT/uXBxHHFNs3ji30UN/9tVmdUr2wofwhF+o3Vtb35pVFL/40JP2ABzJqECNqCio5alYJjgtXT0nZLGshReRqOLP9V/XsiciK95JmxNNRT78qz5J9Blio1bkrU0MkFNkA1BVSizUvpo6JQpGcN3uOslNKAN+y1SoM2YZhTwMOR4j3Q5jNJuJZHTMFldZFJxVi1r4LpR2Bp5LS0dy0=
